name: pylabdd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - gfortran
  - pytest
  - ipython
  - ipykernel
  - jupyterlab
  - notebook
  - nb_conda_kernels

