name: pylabdd
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - gfortran
  - pytest
  - ipython
  - ipykernel
  - jupyterlab
  - notebook
  - nb_conda_kernels
  - h5py
  - hdf5
  - pkg-config

