name: Build and publish to TestPyPI

on:
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build module
        run: python -m pip install build

      - name: Build sdist
        run: python -m build --sdist --outdir dist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install gfortran on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install gcc
          echo "Installed gfortran version:"
          gfortran --version
  
      - name: Build wheels
        run: pip wheel -w dist/ .

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python }}
          path: dist/*.whl

  publish_testpypi:
    name: Upload to TestPyPI
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Install twine
        run: python -m pip install --upgrade twine
  
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Move all distributions to dist/
        run: |
          mkdir -p dist
          find artifacts -name "*.whl" -exec cp {} dist/ \;
          find artifacts -name "*.tar.gz" -exec cp {} dist/ \;

      - name: Install twine
        run: python -m pip install twine

      - name: Check distributions
        run: python -m twine check dist/*

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
