name: Build and publish to TestPyPI

on:
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build module
        run: python -m pip install build

      - name: Build sdist
        run: python -m build --sdist --outdir dist/

  build_wheels:
    name: Build wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install gfortran on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install gcc
          echo "Installed gfortran version:"
          gfortran --version
  
      - name: Build wheels
        run: pip wheel -w dist/ .

  publish_testpypi:
    name: Upload to TestPyPI
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    steps:
      - name: Install twine
        run: python -m pip install --upgrade twine

      - name: Check distribution metadata
        run: twine check dist/*

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: twine upload dist/*
